language: "node_js"
node_js:
  - "5.4.1"
before_install:
  - "rvm install 2.3.0"
install:
  - npm install
  - "bundle install --path vendor/bundle"
after_success:
  - npm run build
before_deploy:
  - "npm install -g surge"
deploy:
  provider: script
  script: "surge ./public"
  skip_cleanup: true
  on:
    branch: master
